name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
          target: x86_64-pc-windows-msvc  # Only needed for Windows
        if: matrix.os == 'windows-latest'

      - name: Install Rust (Linux)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
        if: matrix.os == 'ubuntu-latest'

      - name: Check for Rust project
        id: check_rust
        shell: bash
        run: echo "exists=$( [ -f Cargo.toml ] && echo 'true' || echo 'false' )" >> $GITHUB_OUTPUT

      - name: Format check
        if: steps.check_rust.outputs.exists == 'true'
        run: cargo fmt --all -- --check

      - name: Lint
        if: steps.check_rust.outputs.exists == 'true'
        run: cargo clippy -- -D warnings

      - name: Run tests
        if: steps.check_rust.outputs.exists == 'true'
        run: cargo test --workspace